name: Create releases
on:
  push:
    branches:
      - master

jobs:
  release:
    name: release
    if: github.ref == 'refs/heads/master' && github.repository == 'openai/openai-node'
    runs-on: ubuntu-latest
    environment: publish

    steps:
      - uses: actions/checkout@v3

      - uses: stainless-api/trigger-release-please@v1
        id: release
        with:
          repo: ${{ github.event.repository.full_name }}
          stainless-api-key: ${{ secrets.STAINLESS_API_KEY }}

      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: 'openai'
          repositories: 'openai-node,openai-deno-build'

      - name: Set up Node
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set up Deno
        if: ${{ steps.release.outputs.releases_created }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install dependencies
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          yarn install

      - name: Publish to NPM
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          bash ./bin/publish-npm
        env:
          NPM_TOKEN: ${{ secrets.OPENAI_NPM_TOKEN || secrets.NPM_TOKEN }}

      - name: Publish to Deno
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          bash ./scripts/git-publish-deno.sh
        env:
          DENO_PUSH_REMOTE_URL: https://username:${{ steps.generate_token.outputs.token }}@github.com/openai/openai-deno-build.git
          DENO_PUSH_BRANCH: main
